### ISSUE TITLE
Interaction clusters for 3x3 two way ANOVA

### ISSUE THREAD

**Issue by jinhee615** [tramarobin/fctSPM#14]
Hello. I'm trying to run 3x3 two way repeated ANOVA.

Significant interaction occured, and Now I want to interpret it by observing graphs and clusters.

I have Three Groups(I,N,O), Three Conditions(In-toed, Normal, Out-toed).

![image](https://user-images.githubusercontent.com/82136393/115841280-98f16900-a457-11eb-948a-e78300b8d346.png)
Images above showed in Post hoc > Group x Condition > Condition. (Right Image is I + SPM, N + SPM, O + SPM each.)

As You See, there are total 7 areas of significance in I-O comparsion, 3 significances in N-O comparison. (3rd, 4th columns)

I tried to find clusters with code
spmAnalysis2.posthoc{1,3}.tTests.clusterLocation
spmAnalysis2.posthoc{1,3}.tTests.clusterP
![image](https://user-images.githubusercontent.com/82136393/115841381-b0c8ed00-a457-11eb-9bd9-9289e05667a9.png)
![image](https://user-images.githubusercontent.com/82136393/115843324-ad366580-a459-11eb-815e-e1df49c50ba1.png)

My questions are,
1) why there is 1x11 cells, and most of them are 0?

![image](https://user-images.githubusercontent.com/82136393/115841818-2634bd80-a458-11eb-9eac-b4dceb314004.png)
 
2) What does cluster location in above image means?
 cluster location is [0, 18.5854], [97.2447,100]
But none of graph(in folder Group x Condition > Condition > SPM) seems to have those cluster location.

Thanks in advance!

**Comment by jinhee615** [comment]
> Before you spend more time interpreting the graphs, make sure to increase the number of iterations with the `multiIT` optional input. Defining this value at 1000 will stabilized the F and T thresholds to have a reproductible analysis.

I couldn' find multiIT function. can you tell me an example to run it?


> You are here in the 11th t-test, and judging by the values the comparison is Intoed - Outtoed for the group N.

Can you tell me how did you know 11th is Intoed-Outtoed Group N? (t-test order)

I thought t-test order like below
1. Intoe(I-N),
2. Intoe(I-O),
3. Intoe(N-O),
4.Normal(I-N),
5.Normal(I-O),
6.Normal(O-N)
7.Outtoe(I-N),
8.Outtoe(I-O),
9.Outtoe(O-N),
10.I (Intoe-Normal),
11.I (Intoe-Outtoe),
12.I (Normal-Outtoe)
13.N (Intoe-Normal),
14.N (Intoe-Outtoe),
15.N (Normal-Outtoe),
16.O (Intoe-Normal)
17.O(Intoe-Outtoe)
18.O (Normal-Outtoe),

**Comment by tramarobin** [comment]
> I couldn' find multiIT function. can you tell me an example to run it?

You can find the list of all the optinal inputs [here](https://github.com/tramarobin/fctSPM#optional-inputs), and more precisely [here](https://github.com/tramarobin/fctSPM#statistical-parameters) for `multiIT` : 

`multiIT` define the number of permutations as multiIT/alpha. Default is 10, corresponds to 200 iterations for 5% risk.

```matlab
spmAnalysis=fctSPM(data, independantEffects, repeatedMeasuresEffects, 'multiIT', 500)
```

I suggest here a value of 500, permitting to do 500/alpha iterations so 10000 iterations for an alpha risk of 5%. However, as the critical p-value decrease with the number of post hoc tests (0.05/18 = 0.0028), the number of iterations will still be 10000. 
If you want to override the limit of 10000 iterations (which was put in place to avoid too great computing time), use `maximalIT` and define the value of your convenience. 

for instance :
```matlab
spmAnalysis=fctSPM(data, independantEffects, repeatedMeasuresEffects, 'multiIT', 500, 'maximalIT', 20000)
```
Here, even if the p-value to achieve significance is 0.0028 a number of iterations will be set at ~178000, this value will be decrease at 20000. This is of course sufficient because 20000 iterations allow an accuracy of the p-value of 1/20000 = 0.00005, which is 5 times greater than 0.0028. If you want to know more about the permutations tests, I recommend you [this article](https://pubmed.ncbi.nlm.nih.gov/11747097/) : Nichols TE, Holmes AP (2002). Nonparametric permutation tests for functional neuroimaging: a primer with examples. Human Brain Mapping 15(1), 1–25.
 

> Can you tell me how did you know 11th is Intoed-Outtoed Group N? (t-test order)

It was just a guess with the graph you showed me.
The simpler way to know what comparison is performed is too look at `spmAnalysis.posthoc{3}.tTests.names`

**Comment by jinhee615** [comment]
Thanks!
My code now is : spmAnalysis2=fctSPM(Y2,independantEffects,repeatedMeasuresEffects,'effectsNames',effectNames);
to use multiIT, it is okay to change like below?
spmAnalysis2=fctSPM(Y2,independantEffects, repeatedMeasureEffects, 'multiiT','500,'maximalIT',20000); 


and one more,
In t-test, Can I know 'How much' difference in which variables? 
For example, "NO group showed n~n(degree) larger ankle eversion angle than NI group".

**Comment by tramarobin** [comment]
> My code now is : spmAnalysis2=fctSPM(Y2,independantEffects,repeatedMeasuresEffects,'effectsNames',effectNames);
to use multiIT, it is okay to change like below?
spmAnalysis2=fctSPM(Y2,independantEffects, repeatedMeasureEffects, 'multiiT','500,'maximalIT',20000);

Yes it is ok to change it like this. You can add as many as optional inputs in the function, this can allow you to personalized figures directly. The only order of importance are for the three firsts inputs. For instance :

``` matlab
spmAnalysis2=fctSPM(Y2,independantEffects, repeatedMeasureEffects, 'effectsNames', effectNames, 'multiiT', 500 , 'maximalIT', 20000);
```

> In t-test, Can I know 'How much' difference in which variables?


In the folder 'Post hoc/Group x Condition/DIFF', you can find graphs with differences and relative differences. 
For your Group effect the difference is the mean difference while for your Condition effect the graphs show the mean and the standard deviation. 
You can also use the effect sizes 'Post hoc/Group x Condition/ES' to interpret your results. However, they have not been validated and can just give you an idea of the magnitude of the differences.

To obtain values (and not graphs), you can look at `spmAnalysis.posthoc.differences.continuum` and `spmAnalysis.posthoc.differences.continuumRelative` in which the differences and relatives differences are calculated.

**Comment by jinhee615** [comment]
Thank You so much!
